#!/bin/sh

# AppBackup
# An iOS application that backs up and restores the saved data and
# preferences of App Store apps.
#
# Copyright (C) 2008-2014 Scott Zeid
# https://s.zeid.me/projects/appbackup/
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
# 
# Except as contained in this notice, the name(s) of the above copyright holders
# shall not be used in advertising or otherwise to promote the sale, use or
# other dealings in this Software without prior written authorization.

# GUI runner

LOG_ROOT=/var/mobile/Library/Preferences/AppBackup/logs
LOG_PATH_FIXPERMISSIONS_OUT_TMP=/tmp/AppBackup-FixPermissions-touched.log
LOG_PATH_FIXPERMISSIONS_TMP=/tmp/AppBackup-FixPermissions-errors.log
LOG_PATH_FIXPERMISSIONS_OUT="$LOG_ROOT"/FixPermissions-touched.log
LOG_PATH_FIXPERMISSIONS="$LOG_ROOT"/FixPermissions.log
LOG_PATH_APPBACKUPGUI="$LOG_ROOT"/AppBackupGUI.log

username=`id -un`

log_if_mobile() {
 # Log debugging info if we're running as the mobile user
 # (which should always be true, but it's always good to be safe)
 local log_file="$1"
 local r=127
 shift
 if [ x"$username" = x"mobile" ]; then
  "$@" &> "$log_file"; r=$?
 else
  "$@"; r=$?
 fi
 printf '\n%s\n' "(\`$@\` returned with code $r)" &>> "$log_file"
 return $r
}

# Fix permissions on user directory (This is a binary with setuid root)
# Make a blank file in /Applications/AppBackup.app called NoFixPermissions to
# disable this.
fix_permissions() {
 "$(dirname "$0")"/FixPermissions > "$LOG_PATH_FIXPERMISSIONS_OUT_TMP";
}
if [ ! -e "$(dirname "$0")/NoFixPermissions" ]; then
 log_if_mobile "$LOG_PATH_FIXPERMISSIONS_TMP" fix_permissions
else
 echo "(FixPermissions disabled by user)" &> "$LOG_PATH_FIXPERMISSIONS_TMP"
fi

# Make the debug directory if it does not exist, but only if
# /var/mobile/Library/Preferences is a directory and we're mobile
# (as we should be).  Also move the FixPermissions logs to there if
# applicable.
debug_grandparent_dir="$(dirname "$(dirname "$LOG_ROOT")")";
if [ -d "$debug_grandparent_dir" ] && [ x"$username" = x"mobile" ]; then
 mkdir -p "$LOG_ROOT"
 if [ -e "$LOG_PATH_FIXPERMISSIONS_OUT_TMP" ]; then
  mv "$LOG_PATH_FIXPERMISSIONS_OUT_TMP" "$LOG_PATH_FIXPERMISSIONS_OUT"
 fi
 if [ -e "$LOG_PATH_FIXPERMISSIONS_TMP" ]; then
  mv "$LOG_PATH_FIXPERMISSIONS_TMP" "$LOG_PATH_FIXPERMISSIONS"
 fi
fi

# Run the GUI and log debugging info if we're mobile (which we should be)
cd "$(dirname "$0")"
log_if_mobile "$LOG_PATH_APPBACKUPGUI" exec "$(dirname "$0")/AppBackupGUI_" "$@"
