#!/bin/bash

DEVICE=scottPhone

if [ ! "$1" = "" ]; then
 DEVICE=$1
fi

cd "$(dirname "$0")"

PREFIX="test_"
./build $PREFIX
DEBFILE=`ls | grep "^test_.*\.deb$"`

scp "$DEBFILE" mobile@$DEVICE:/tmp
ssh root@$DEVICE "dpkg -i /tmp/$DEBFILE && rm /tmp/$DEBFILE"
ssh mobile@$DEVICE "tail -fn0 ~/Library/Preferences/AppBackup/debug.log"
ssh mobile@$DEVICE
