#!/bin/bash

DEVICE=$1
if [ "$1" = "" ]; then
 echo "Usage: $0 device-address"
 exit 2
fi

cd "$(dirname "$0")"

# Build .deb
./build $DEVICE test_
DEBFILE=`ls | grep "^test_.*\.deb$"`

# Test on device
scp "$DEBFILE" mobile@$DEVICE:/tmp
ssh root@$DEVICE "dpkg -i /tmp/$DEBFILE && rm /tmp/$DEBFILE"
ssh mobile@$DEVICE "tail -fn0 ~/Library/Preferences/AppBackup/debug.log"
ssh mobile@$DEVICE
