#!/bin/bash

# AppBackup
# An iPhoneOS application that backs up and restores the saved data and
# preferences of App Store apps.
#
# Copyright (C) 2008-2010 Scott Wallace
# http://pages.srwz.us/iphone/appbackup
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Loosely based on Dave Arter's (dave@minus-zero.org) sample code from the
# iPhone/Python package.

# Fix permissions on user directory (This is a binary with setuid root)
# Make a blank file in /Applications/AppBackup.app called NoFixPermissions to
# disable this.
if [ ! -e "$(dirname "$0")/NoFixPermissions" ]; then
 "$(dirname "$0")"/FixPermissions > /tmp/FixPermissions.log
fi

# path to Python
PYTHON_PATH="$(dirname "$0")"/AppBackupPython
# path to script
APPBACKUP_SCRIPT="$(dirname "$0")"/App.py
# set to 1 to enable debugging; 0 to disable
DEBUG_APP=1
if [ -e "/var/mobile/Library/AppBackup" -a ! -e "/var/mobile/Library/AppBackup/This has been moved" ]; then
 LIBROOT="/var/mobile/Library/AppBackup"
else
 LIBROOT="/var/mobile/Library/Preferences/AppBackup"
fi
# Make $LIBROOT if it doesn't exist
mkdir -p $LIBROOT
# location of log file for debugging
APPBACKUP_DEBUG_FILE="$LIBROOT/debug.log"

touch $APPBACKUP_DEBUG_FILE
if [ "$DEBUG_APP" -eq "1" ]; then
 # with debugging
 exec $PYTHON_PATH -dO $APPBACKUP_SCRIPT "$@" &>$APPBACKUP_DEBUG_FILE
else
 # without debugging
 exec $PYTHON_PATH -O $APPBACKUP_SCRIPT "$@"
fi
