#!/bin/bash

chown -R root:wheel /Applications/AppBackup.app

echo ""
echo "If you have any problems with AppBackup,"
echo "please contact the author, Scott Wallace, by"
echo "going to <http://www.scott-wallace.net/contact> on"
echo "your computer.  Please be sure to attach this file:"
echo "/var/mobile/Library/Preferences/AppBackup/debug.log"
