#!/bin/bash

# AppBackup
# An iPhoneOS application that backs up and restores the saved data and
# preferences of App Store apps.
#
# Copyright (C) 2008-2009 Scott Wallace
# http://www.scott-wallace.net/iphone/appbackup
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#
# Loosely based on Dave Arter's (dave@minus-zero.org) sample code from the
# iPhone/Python package.

# path to Python
PYTHON_PATH="$(dirname "$0")"/AppBackupPython
# path to script
APPBACKUP_SCRIPT="$(dirname "$0")"/App.py
# set to 1 to enable debugging; 0 to disable
DEBUG_APP=1 # Debug logging is now done in App.py itself to reduce system noise
# Make ~mobile/Library/AppBackup if it doesn't exist
mkdir -p /var/mobile/Library/AppBackup
# location of log file for debugging
APPBACKUP_DEBUG_FILE="/var/mobile/Library/AppBackup/debug.log"

export PYTHONPATH="$(dirname "$0")/modules:$PYTHONPATH"
if [ "$DEBUG_APP" -eq "1" ]; then
 # with debugging
 exec $PYTHON_PATH -dO $APPBACKUP_SCRIPT "$@"
 #&>$APPBACKUP_DEBUG_FILE
else
 # without debugging
 exec $PYTHON_PATH -O $APPBACKUP_SCRIPT "$@"
fi
